language: php
php: 7.2

before_script: compose install -n

script:
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=./tests/_support/* ./src ./tests
  - ./vendor/bin/codecept --steps --coverage
