version: "3"
services:
  mysql:
    image: mysql:5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=root

  php:
    image: sql-documentor
    depends_on:
      - mysql
    volumes:
      - ./:/sql-documentor
    user: 1000:1000
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TARGET_DIRECTORY=/sql-documentor/docs/
      - YML_DIRECTORY=/sql-documentor/yml/
